routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('auth', 'isAdmin')->prefix('admin')->group(function () {
    Route::get('/', \App\Http\Controllers\admin\main\IndexController::class);
    Route::prefix('movie')->group(function () {
        Route::get('/', [\App\Http\Controllers\admin\movie\MovieController::class, 'index'])->name('admin.movie.index');
        Route::post('/', [\App\Http\Controllers\admin\movie\MovieController::class, 'store'])->name('admin.movie.store');
        Route::get('/show/{movie}', [\App\Http\Controllers\admin\movie\MovieController::class, 'show'])->name('admin.movie.show');
        Route::get('/create', [\App\Http\Controllers\admin\movie\MovieController::class, 'create'])->name('admin.movie.create');
        Route::get('/edit/{movie}/', [\App\Http\Controllers\admin\movie\MovieController::class, 'edit'])->name('admin.movie.edit');
        Route::patch('/edit/{movie}/', [\App\Http\Controllers\admin\movie\MovieController::class, 'update'])->name('admin.movie.update');
        Route::delete('/delete/{movie}/', [\App\Http\Controllers\admin\movie\MovieController::class, 'delete'])->name('admin.movie.delete');
    });
    Route::prefix('seans')->group(function () {
        Route::get('/', [\App\Http\Controllers\admin\seans\SeansController::class, 'index'])->name('admin.seans.index');
        Route::post('/', [\App\Http\Controllers\admin\seans\SeansController::class, 'store'])->name('admin.seans.store');
        Route::get('/create', [\App\Http\Controllers\admin\seans\SeansController::class, 'create'])->name('admin.seans.create');
        Route::get('/show/{seans}/', [\App\Http\Controllers\admin\seans\SeansController::class, 'show'])->name('admin.seans.show');
        Route::get('/show/{seans}/edit', [\App\Http\Controllers\admin\seans\SeansController::class, 'edit'])->name('admin.seans.edit');
        Route::patch('/show/{seans}/edit', [\App\Http\Controllers\admin\seans\SeansController::class, 'update'])->name('admin.seans.update');
        Route::delete('/delete/{seans}/', [\App\Http\Controllers\admin\seans\SeansController::class, 'delete'])->name('admin.seans.delete');
    });
});

Route::get('/', [\App\Http\Controllers\front\CinemaController::class, 'index'])->name('cinema.index');


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Movie.php
<?php

namespace App\Models;

use Carbon\CarbonInterval;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Movie extends Model
{
    use HasFactory;
    protected $guarded = false;
    protected $table = 'movies';

    public function image(): HasOne
    {
        return $this->hasOne(MoviePicture::class);
    }

    public function getAgeAttribute(): string
    {
        return Age::where('id', $this->age_id)->pluck('age')->first() . '+';
    }

    public function getTimeAttribute()
    {
        return CarbonInterval::seconds($this->duration)->cascade()->forHumans();
    }


}

app/Http/Controllers/admin/movie/MovieController.php
<?php

namespace App\Http\Controllers\admin\movie;

use App\Http\Controllers\Controller;
use App\Http\Requests\Movie\StoreRequest;
use App\Http\Requests\Movie\UpdateRequest;
use App\Models\Age;
use App\Models\Movie;
use App\Models\MoviePicture;
use Illuminate\Support\Facades\Storage;

class MovieController extends Controller
{
    public function index()
    {
        $movies = Movie::query()->latest()->get();
        return view('admin.movie.index', compact('movies'));
    }

    public function show(Movie $movie)
    {
        return view('admin.movie.show', compact('movie'));
    }

    public function edit(Movie $movie)
    {
        $ages = Age::all();
        return view('admin.movie.edit', compact('movie', 'ages'));
    }

    public function create()
    {
        $ages = Age::all();
        return view('admin.movie.create', compact('ages'));
    }

    public function store(StoreRequest $request)
    {
        $data = $request->validated();
        $image = $data['image'];
        unset($data['image']);
        $movie = Movie::firstOrCreate($data);
        $path = Storage::disk('public')->putFileAs('/images/movie',$image, $movie->id . '.jpg', $image);
        $url = $request->root() . '/storage/' . $path;
        MoviePicture::create([
            'path' => $path,
            'url' => $url,
            'movie_id' => $movie->id
        ]);
        return redirect()->route('admin.movie.index');
    }

    public function update(UpdateRequest $request, Movie $movie)
    {
        $data = $request->validated();
        if (isset($data['image'])) {
            $image = $data['image'];
            unset($data['image']);
            $path = Storage::disk('public')->putFileAs('/images/movie',$image, $movie->id . '.jpg', $image);
            $url = $request->root() . '/storage/' . $path;
            MoviePicture::query()->update([
                'path' => $path,
                'url' => $url,
                'movie_id' => $movie->id
            ]);

        }

        $movie->update($data);
        return redirect()->route('admin.movie.show', $movie->id);
    }

    public function delete(Movie $movie)
    {
        if (isset($movie->image->path)) {
            Storage::disk('public')->delete($movie->image->path);
        }
        $movie->delete();
        return redirect()->route('admin.movie.index');
    }
}

resources/views/admin/movie/create.blade.php
@extends('layouts.admin.main')

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Добавить фильм</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Главная</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <form action="{{ route('admin.movie.store') }}" method="post" enctype="multipart/form-data" class="w-96">
                    @csrf
                    <div class="form-group">
                        <input type="text" name="title" class="form-control" placeholder="название" value="{{ old('title') }}">
                        @error('title')
                        {{ $message }}
                        @enderror
                    </div>
                    <div class="form-group mb-2">
                        <label>Добавить главное фото</label>
                        <div class="custom-file">
                            <input type="file" name="image" multiple class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                            @error('image')
                            {{ $message }}
                            @enderror
                        </div>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="descriptions" placeholder="описание">{{ old('descriptions') }}</textarea>
                        @error('descriptions')
                        {{ $message }}
                        @enderror
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="number" name="duration" placeholder="продолжительность" value="{{ old('duration') }}">
                        @error('duration')
                        {{ $message }}
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Выберете возрастное ограничение</label>
                        <select name="age_id" class="form-control select2" style="width: 100%;">
                            @foreach($ages as $age)
                                <option value="{{ $age->id }}"
                                    {{ $age->id == old('age_id') ? ' selected' : '' }}>
                                    {{ $age->age . '+'}}</option>
                            @endforeach
                        </select>
                    </div>
                    <input type="submit" value="Добавить" class="btn btn-success">
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/movie/edit.blade.php
@extends('layouts.admin.main')

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Изменить фильм</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Главная</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <form action="{{ route('admin.movie.update', $movie->id) }}" method="post" enctype="multipart/form-data" class="w-96">
                    @csrf
                    @method('PATCH')
                    <div class="form-group">
                        <input type="text" name="title" class="form-control" placeholder="название" value="{{ $movie->title }}">
                        @error('title')
                        {{ $message }}
                        @enderror
                    </div>
                    <div class="ml-1 mb-2">
                        <img class="w-25" src="{{ $movie->image->url }}" alt="3333">
                    </div>
                    <div class="form-group mb-2">
                        <label>Обновить главное фото</label>
                        <div class="custom-file">
                            <input type="file" name="image" multiple class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                            @error('image')
                            {{ $message }}
                            @enderror
                        </div>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="descriptions" placeholder="описание">{{ $movie->descriptions }}</textarea>
                        @error('descriptions')
                        {{ $message }}
                        @enderror
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="number" name="duration" placeholder="продолжительность" value="{{ $movie->duration }}">
                        @error('duration')
                        {{ $message }}
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Выберете возрастное ограничение</label>
                        <select name="age_id" class="form-control select2" style="width: 100%;">
                            @foreach($ages as $age)
                                <option value="{{ $age->id }}"
                                    {{ $age->id == $movie->age_id ? ' selected' : '' }}>
                                    {{ $age->age . '+'}}</option>
                            @endforeach
                        </select>
                    </div>
                    <input type="submit" value="Обновить" class="btn btn-success">
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/movie/index.blade.php
@extends('layouts.admin.main')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Фильмы</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Главная</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header flex">
                            <a href="{{ route('admin.movie.create') }}" class="btn btn-primary">Добавить Фильм</a>
                        </div>
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    <th>Название</th>
                                    <th>Фото</th>
                                    <th>Описание</th>
                                    <th>Продолжительность</th>
                                    <th>Возраст</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($movies as $movie)
                                    <tr>
                                        <td><a href="{{ route('admin.movie.show', $movie->id) }}">{{ $movie->title }}</a></td>
                                        <td class="w-25"><img class="w-25" src="{{ $movie->image->url }}" alt="{{ $movie->title }}"></td>
                                        <td>{{ $movie->descriptions }}</td>
                                        <td>{{ $movie->time }}</td>

                                        <td>{{ $movie->Age }}</td>
{{--                                        <td><form action="{{ route('anime.delete', $anime->id) }}" method="post">--}}
{{--                                                @csrf--}}
{{--                                                @method('delete')--}}
{{--                                                <input type="submit" value="Удалить" class="btn btn-danger">--}}
{{--                                            </form></td>--}}
{{--                                    </tr>--}}
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
{{--                    <div class="flex justify-content-center">--}}
{{--                        {{ $movies->links() }}--}}
{{--                    </div>--}}
                </div>
            </div>
        </div>
    </section>
@endsection

<style>

</style>

resources/views/admin/movie/show.blade.php
@extends('layouts.admin.main')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Фильмы</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Главная</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header flex">
                            <a href="{{ route('admin.movie.edit', $movie->id) }}" class="btn btn-primary">Изменить Фильм</a>
                        </div>
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    <th>Название</th>
                                    <th>Фото</th>
                                    <th>Описание</th>
                                    <th>Продолжительность</th>
                                    <th>Возраст</th>
                                    <th>Удаление</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr>

                                        <td>{{ $movie->title }}</td>
                                        <td class="w-25"><img class="w-25" src="{{ $movie->image->url }}" alt="{{ $movie->title }}"></td>
                                        <td>{{ $movie->descriptions }}</td>
                                        <td>{{ $movie->time }}</td>
                                        <td>{{ $movie->age }}</td>
                                        <td><form action="{{ route('admin.movie.delete', $movie->id) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <input type="submit" value="Удалить" class="btn btn-danger">
                                            </form></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

<style>

</style>